### ISSUE TITLE
About generating intensity images from point clouds

### ISSUE THREAD

**Issue by Karry11** [koide3/direct_visual_lidar_calibration#33]
Hello, thank you for your great work, but as a beginner, I have a question about generating intensity images from point clouds. In paper, you create a virtual camera when get point clouds from livox (Am I understanding it correctly?). Does this mean that I need to know the camera's internal parameters, distortion parameters, radar placement, orientation, and spatial position in advance? I don't think I need external parameters, because my goal is to solve for external parameters. And then use this virtual camera to project the point cloud data onto the image? Does this result in inaccurate projection of the point cloud position onto the image?

**Comment by koide3** [comment]
It first estimates the FoV of the LiDAR and then creates a virtual camera such that the camera's FoV matches the LiDAR's FoV (See [here](https://github.com/koide3/direct_visual_lidar_calibration/blob/c7730fdf0d94033a67ecbe0270905c0973351440/src/vlcal/preprocess/preprocess.cpp#L176C1-L176C1)). Because the process is fully automatic, you don't need to know any parameters at this step. 
The virtual camera (and generated intensity images) are used solely for visual feature matching, and thus does affect projection (and calibration) results.
