### ISSUE TITLE
How to set parameters

### ISSUE THREAD

**Issue by Eric5709** [koide3/direct_visual_lidar_calibration#55]
**Thanks for your great research!**

I have two questions.

1. I've heard that even small change can lead to significant differences in sensor calibration.
When I adjust the parameter `robust_kernel_width` in function  _"estimate_rotation_ransac"_ at _"estimate_pose.cpp"_, result changes significantly. So it seems necessary to determine the correct parameters for different dataset.
Could you please provide guidance on how to set appropriate parameters like `robust_kernel_width` or `error_thresh_sq`?

2. I've noticed a step that identifies `inliers` in the "estimate_rotation_ransac" function, but it appears that this information is never utilized. I'm curious why the code estimates the pose using all correspondences rather than just the `inliers` in the _"estimate_pose_lsq"_ function.

Thanks!

**Comment by koide3** [comment]
1. `robust_kernel_width` changes the sensitivity to outliers in 2D-3D correspondences. If your data contains many wrong correspondences decrease this parameter to filter out them.
2. Because we use robust kernels in the LSQ optimization, we can expect that outliers are automatically removed. We thus simply gave it all correspondences.

**Comment by Eric5709** [comment]
Thank you for the kind response!
